[workspace]

members = [  # cargo run -p <member>
    "backend",  # cargo run -p backend
    "tester",  # cargo run -p tester
]

default-members = [  # cargo run
    "backend",
]

# the resolver version is used for all crates in the workspace
resolver = "2"
